### ISSUE TITLE
Change variable names accordingly to its type

### ISSUE THREAD

**Issue by DoktorZAG** [dvddhln/quarkus-reactive-hibernate-graphql-crud#2]
In the following lines the names of the local variable are "switched": Movie is named as an actor, and an Actor is named as movie:

It would be great to fix the typo 🙂

https://github.com/dvddhln/quarkus-reactive-hibernate-graphql-crud/blob/a4d54cceb43981eb6de5f72553cc1db2394af9c9/src/main/java/entity/Actor.java#L54
https://github.com/dvddhln/quarkus-reactive-hibernate-graphql-crud/blob/a4d54cceb43981eb6de5f72553cc1db2394af9c9/src/main/java/entity/Actor.java#L55

**Comment by dvddhln** [comment]
Sorry about that, should be fixed and reflected in the gist. Thanks for noticing :)
